### ISSUE TITLE
initSync not found

### ISSUE THREAD

**Issue by smessmer** [rustyscreeps/screeps-arena-starter-rust#4]
Commit 19235b5 broke this repository. Running the example in Screeps Arena fails with

```
SyntaxError: The requested module './screeps-arena-starter-rust' does not provide an export named 'initSync'
    at (<isolated-vm boundary>)
```

Reverting that commit makes it work again.

Looking at the generated javascript file, it looks like there is no "initSync" but there is an init function which is default exported.

**Comment by shanemadden** [comment]
Fixed import syntax for current bindgen in #6
